apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240516124544.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240516124544.0.0+build.6aff574
  releaseNotes: |
    Release v20240516124544.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-15-05-2024-21-56-25-431543299/where-for-dinner-my-apps-bundle@sha256:2cb3cdb50beea0c0c94d2c4208f50d4f0ce9027fa4b5517ceeb3c67b7f75341d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

